# Generated by Django 4.2.3 on 2023-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_berry_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='berry',
            name='id',
        ),
        migrations.AlterField(
            model_name='berry',
            name='slug',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
