# Generated by Django 4.2.3 on 2023-08-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_decor_remove_berry_id_alter_berry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
