# Generated by Django 4.2.3 on 2023-08-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='delivery_conditions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
