# Generated by Django 4.2.3 on 2023-08-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutus_delivery_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='berries',
            field=models.ManyToManyField(related_name='berries', to='core.berry'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decors',
            field=models.ManyToManyField(related_name='decors', to='core.decor'),
        ),
    ]
