# Generated by Django 4.2.3 on 2023-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cake_berries_cake_decors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='signature',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
