# Generated by Django 4.2.3 on 2023-08-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cake_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='berry',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cake',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.ManyToManyField(blank=True, related_name='berries', to='core.berry'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decors',
            field=models.ManyToManyField(blank=True, related_name='decors', to='core.decor'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cake',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cake',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shape'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topping'),
        ),
    ]
