# Generated by Django 4.2.3 on 2023-08-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_level_shape_topping_berry_price_cake_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berries',
            field=models.ManyToManyField(blank=True, to='core.berry'),
        ),
    ]
