# Generated by Django 4.2.3 on 2023-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cake_berries'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='timeslot',
            field=models.IntegerField(choices=[('1', '10-12'), ('2', '12-14'), ('3', '14-16'), ('4', '16-18'), ('5', '18-20')], default=1),
        ),
    ]
