# Generated by Django 4.2.3 on 2023-08-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cake_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cake',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='cake',
            name='delivery',
            field=models.IntegerField(choices=[(0, 'Самовывоз'), (1, 'Доставка')], default=0),
        ),
        migrations.AddField(
            model_name='cake',
            name='ready_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cake',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отменен'), (3, 'Приготовить'), (4, 'Доставить'), (5, 'Выполнен')], default=1),
        ),
        migrations.AlterField(
            model_name='cake',
            name='timeslot',
            field=models.IntegerField(choices=[(1, '10-12'), (2, '12-14'), (3, '14-16'), (4, '16-18'), (5, '18-20')], default=1),
        ),
    ]
