# Generated by Django 4.2.3 on 2023-08-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cake_address_cake_comment_cake_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='complete',
        ),
        migrations.AlterField(
            model_name='cake',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cake',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cake',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отменен'), (3, 'Приготовить'), (4, 'Доставить'), (5, 'Выполнен'), (6, 'Образец')], default=1),
        ),
    ]
